In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


# *Tensors*

Pytorch tensor are created using torch.tensor() - https://pytorch.org/docs/stable/torch.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Gett tensor back as python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random Tensors

In [17]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2287, 0.3780, 0.5532, 0.1297],
        [0.9654, 0.7015, 0.9298, 0.8165],
        [0.7513, 0.6161, 0.6220, 0.7818]])

In [18]:
random_tensor.ndim

2

In [19]:
# random_tensor = torch.rand(5,5,5)
# random_tensor

In [20]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
## Create tensor ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32

## Creating a range of tensor and tensor-like

In [26]:
torch.range(0,10)

<ipython-input-26-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
one_to_ten = torch.arange(start = 0,end =1000,step = 77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [28]:
#Creating tensor like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatype

### Tensor Datatypes

**NOTE:** Tensor Datatypes is one of the 3 big erros you will run into with Pytorch and deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [29]:
## FLoat 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype = None)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype

torch.float32

In [31]:
## FLoat 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype = torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
## FLoat 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
## Shaping 32 tensor into 16

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [36]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)

## Getting Information from tensor

1. Tensor not right datatype - to do get datatype from a tensor, can use tensor.dtype
2.Tensor not right shape - to get shape froma a tensor, can use tensor.shape
3. Tensor not on right device - to get device from a tensor, can use tensor.device

In [37]:
## Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9773, 0.8984, 0.5633, 0.9250],
        [0.1925, 0.6635, 0.0253, 0.9564],
        [0.3112, 0.8305, 0.1771, 0.7117]])

In [38]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [39]:
## find out details
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Datatype of tensor: {some_tensor.size}")
print(f"Datatype of tensor: {some_tensor.device}")

tensor([[0.9773, 0.8984, 0.5633, 0.9250],
        [0.1925, 0.6635, 0.0253, 0.9564],
        [0.3112, 0.8305, 0.1771, 0.7117]])
Datatype of tensor: torch.float32
Datatype of tensor: <built-in method size of Tensor object at 0x7891f3f817b0>
Datatype of tensor: cpu


In [40]:
## Manipulating Tensor(Tensor Operations)

# Tensor operations include:
# add
# sub
# multiply(element-wise)
# devision
# Matrix multiplication

In [41]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor = tensor+10
tensor

tensor([11, 12, 13])

In [42]:
tensor = tensor*10
tensor

tensor([110, 120, 130])

In [43]:
# subtract
tensor = tensor-10
tensor

tensor([100, 110, 120])

In [44]:
# Try out Pytorch in built functions
torch.mul(tensor,10)

tensor([1000, 1100, 1200])

In [45]:
torch.add(tensor,1)

tensor([101, 111, 121])

# Matrix Multiplication

Two main ways to perform matrix multiplication in neural network and deep learning

1. Element-wise multiplication
2. Matrix Multiplication(Dot Product)

In [46]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])
print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [47]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [48]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.06 ms, sys: 1.01 ms, total: 2.07 ms
Wall time: 2.62 ms


In [49]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 627 µs, sys: 93 µs, total: 720 µs
Wall time: 626 µs


tensor(14)

# Shape Errors

In [50]:
# Shape of Matrix Multiplication

tensor_A = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [51]:
torch.mm(tensor_A, tensor_B)   #Torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [52]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#### To fix our tensor shape issues, we can manipulate the shapes of one of our tensor using a transpose.



In [53]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [54]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

## Finding the min,max,mean,sum,etc(tensor aggregation)

In [55]:
# Create a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [57]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [58]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [59]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [60]:
#Find the sum

torch.sum(x),x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
#Find the position in tensor that has the minimum value with argmin() - > return index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [65]:
#Find the position in tensor that has the maximum value with argmax() - > return index position of target tensor where the minimum value occurs
x.argmax()

tensor(9)

# Reshaping, stacking ,sequeezing and unsqueezing tensor

* Reshaping - Reshape an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor

* Stacking - Combine multiple tensors on top of each other(VStack) or side by side(hStack)

* Squeeze - remove all 1 dimensions from tensor

* UnSqueeze - add a 1 dimension to to target tensor

* Permute - Return a view of the input with dimensions permuted(Swaped) in certain way

In [1]:
# Lets create a tensor

import torch

x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
## Add an extra Dimension
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [7]:
## Add an extra Dimension
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [13]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [14]:
# Chaning z changes x (because a view of a tensor shares the same memory as the original input)

In [16]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [17]:
# Stack tensors on top of each other

In [20]:
x_stacked = torch.stack([x,x,x,x],dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [21]:
# Kind of H Stack
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [22]:
## Sequeez

In [25]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [27]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
## Unsequeez

In [29]:
squeezed = x_reshaped.squeeze()

In [33]:
x_unsqueezed = squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [34]:
x_unsqueezed = squeezed.unsqueeze(dim=1)
x_unsqueezed,x_unsqueezed.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [35]:
## Torch.Permute - rearranges the dimensions of a target tensor in a specified order

In [37]:
x_original =  torch.rand(size=(224,224,3)) #Image

In [39]:
x_original.shape

torch.Size([224, 224, 3])

In [38]:
x_permuted = x_original.permute(2,0,1)

In [40]:
x_permuted.shape

torch.Size([3, 224, 224])

In [41]:
x_original[0,0,0] = 2222

In [42]:
x_original[0,0,0]

tensor(2222.)

In [43]:
x_permuted[0,0,0]

tensor(2222.)

## Indexing(selecting data from tensor)


#Indexing with Pytorch is very similar to indexing with numpy

In [46]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [48]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [49]:
x[0,0]

tensor([1, 2, 3])

In [51]:
x[0,1]

tensor([4, 5, 6])

In [50]:
x[0,2]

tensor([7, 8, 9])

In [52]:
x[0,0,0]

tensor(1)

In [53]:
x[0,2,2]

tensor(9)

In [55]:
# You can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [56]:
# Get all Values of 0th and 1st dimensions but onlu index of 1 and 2nd dimension


## Pytorch tensors & numPy

numpPy is a popular scientifc Python numerical computing library.

* Data is NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)

* Pytorch tensor -> NumPu -> torch.Tensor.numpy()



In [61]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy-> Pytorch, pytorch reflects numpy's default datatype of float64 unless specifed otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [64]:
# Change the value of array, what will this do to tensor??
array = array+1
array,tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
 # Tensor to Numpy
 tensor = torch.ones(7)
 numpy_tensor = tensor.numpy()
 tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
tensor = tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility(Trying to take random out of random)

In [69]:
torch.rand(3,3)

tensor([[0.6448, 0.1729, 0.5356],
        [0.9531, 0.7787, 0.9866],
        [0.8757, 0.8205, 0.0672]])

In [70]:
# TO REDUCE RANDOMNESS IN NEURAL NETWORK AND PYTORCH COMES THE CONCEPT OF RANDOM SEEDS.
# ESSENTIALLY WHAT THE RANDOM SEED DOES "FLAVOUR" THE RANDOMNESS

In [71]:
import torch

#Create 2 random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)


print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==print(random_tensor_B))

tensor([[0.5486, 0.7626, 0.5447, 0.0094],
        [0.6145, 0.9971, 0.2980, 0.7717],
        [0.3096, 0.8647, 0.1382, 0.6977]])
tensor([[0.5627, 0.1360, 0.5274, 0.7770],
        [0.1539, 0.7436, 0.3929, 0.4724],
        [0.0374, 0.7512, 0.4849, 0.4269]])
tensor([[0.5627, 0.1360, 0.5274, 0.7770],
        [0.1539, 0.7436, 0.3929, 0.4724],
        [0.0374, 0.7512, 0.4849, 0.4269]])
False


In [85]:
# Lets make some random but reproduceable tensors
import torch
# set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(2,2)
random_tensor_d = torch.rand(2,2)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==print(random_tensor_d))

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])
False


In [83]:
# Lets make some random but reproduceable tensors
import torch
# set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(2,2)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(2,2)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[True, True],
        [True, True]])


# Running on GPU

In [1]:
!nvidia-smi

Sat Apr 13 10:23:15 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
## Checking for GPU access with Pytoch

import torch
torch.cuda.is_available()

True

In [5]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available else "cpu"
device

'cuda'

In [6]:
#Count number of GPU

torch.cuda.device_count()

1

## Putting tensor and Models on GPU

In [8]:
# create a tensor(default on the CPU)
tensor = torch.tensor([1,3,3],device="cpu")

print(tensor,tensor.device)

tensor([1, 3, 3]) cpu


In [10]:
# By defalut it it always CPU

# create a tensor(default on the CPU)
tensor = torch.tensor([1,3,3])

print(tensor,tensor.device)

tensor([1, 3, 3]) cpu


In [11]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 3, 3], device='cuda:0')

In [12]:
## Moving Tensor Back to CPU

In [13]:
## If tensor is on GPU can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [14]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 3, 3])

In [15]:
tensor_on_gpu

tensor([1, 3, 3], device='cuda:0')